# Generated by Django 5.2.3 on 2025-06-28 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_purchaseorder_product_purchaseorder_qty_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchasehistory',
            options={'ordering': ['-purchase_date'], 'verbose_name': 'Purchase History', 'verbose_name_plural': 'Purchase Histories'},
        ),
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ['-order_date']},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['stock_id']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='qty',
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETE', 'Complete'), ('CANCEL', 'Cancel')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='stock',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(help_text='Stock Keeping Unit', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='purchasehistory',
            name='purchase_order',
            field=models.ForeignKey(db_column='purchase_order_id', on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='inventory.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='current_qty',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='max_qty',
            field=models.PositiveIntegerField(default=100, help_text='maximum quantity to store'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='min_qty',
            field=models.PositiveIntegerField(default=10, help_text='Minimum quantity'),
        ),
        migrations.AddIndex(
            model_name='purchasehistory',
            index=models.Index(fields=['purchase_order'], name='inventory_p_purchas_4e8bbe_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasehistory',
            index=models.Index(fields=['product', 'purchase_date'], name='inventory_p_product_0a522b_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasehistory',
            index=models.Index(fields=['status', 'purchase_date'], name='inventory_p_status_e46670_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['vendor', 'status'], name='inventory_p_vendor__56d00c_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['product', 'order_date'], name='inventory_p_product_b60e27_idx'),
        ),
    ]
