# Generated by Django 5.2.3 on 2025-06-30 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_purchasehistory_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='vendor_id',
            new_name='vendor',
        ),
    ]
